{
 "title": "Part 7. Prometheus и Grafana",
 "description": "Part 7. Prometheus и Grafana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) without (cpu) * 100",
     "legendFormat": "cpu used"
    }
   ]
  },
  {
   "title": "Free Space HDD",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!='tmpfs'} ",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / 1024"
    }
   ]
  },
  {
   "title": "I/O Operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[5m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}